<?php

function sum_menu() {
    $items['sum'] = array(
        'title' => 'Calculate Sum',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('sum_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['sum_success_page'] = array(
        'title' => 'Result',
        'page callback' => 'sum_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function sum_form() {
    $form['left_number']  = array(
        '#title' => 'First Number',
        '#type' => 'textfield',
        '#description' => t('Please enter your first number.'),
        '#element_validate' => array('element_validate_number', 'element_validate_range', 'element_validate_even'),
        '#required' => TRUE,
    );
    $form['right_number'] = array(
        '#title' => 'Second Number',
        '#type' => 'textfield',
        '#description' => t('Please enter your second number.'),
        '#element_validate' => array('element_validate_number', 'element_validate_range', 'element_validate_even'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Sum',
    );
    $form['button'] ['unsure'] = array(
      '#type' => 'submit',
      '#value' => t('Unsure'),
      '#submit' =>array ('form_unsure'),

    );
$form ['#validate'] = array('form_unsure');
    return $form;
}

function element_validate_range($element) {
    if ($element['#value'] > 50 || $element['#value'] < -50) {
        form_error($element, t('Number must be less than 50 or greater than -50.'));
    }
}

function element_validate_even($element) {
    if ($element['#value'] % 2 != 0) {
        form_error($element, t('Number must be even.'));
    }
}

function sum_form_submit($form, &$form_state) {

    $first_number = $form_state['values']['left_number'];
    $second_number = $form_state['values']['right_number'];
    $sum = $first_number + $second_number;
    $_SESSION['sum_output'] = $sum;


    $form_state['redirect'] = 'sum_success_page';
}
function form_unsure($form, &$form_state){
  drupal_set_message (t('try again'), 'warning');
}

function sum_success() {
    $answer = $_SESSION['sum_output'];
    return 'You calculated a sum! The answer is: ' . $answer;
}
